<div id="Lista">
    <h2>Lista de Automoveis</h2>
    <table>
      <thead>
        <tr>
          <th><h4>Modelo</h4></th>
          <th><h4>Ano</h4></th>
          <th><h4>Cor</h4></th>
          <th><h4>Placa</h4></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><h4>Compass</h4></td>
          <td><h4>2023</h4></td>
          <td><h4>Cinza</h4></td>
          <td><h4>BR-32324</h4></td>
        </tr>
        <tr>
          <td><h4>Compass</h4></td>
          <td><h4>2023</h4></td>
          <td><h4>Cinza</h4></td>
          <td><h4>BR-32324</h4></td>
        </tr>
        <tr>
          <td><h4>Compass</h4></td>
          <td><h4>2023</h4></td>
          <td><h4>Cinza</h4></td>
          <td><h4>BR-32324</h4></td>
        </tr>
        <tr>
          <td><h4>Compass</h4></td>
          <td><h4>2023</h4></td>
          <td><h4>Cinza</h4></td>
          <td><h4>BR-32324</h4></td>
        </tr>
        <tr>
          <td><h4>Compass</h4></td>
          <td><h4>2023</h4></td>
          <td><h4>Cinza</h4></td>
          <td><h4>BR-32324</h4></td>
        </tr>
        <tr>
          <td><h4>Compass</h4></td>
          <td><h4>2023</h4></td>
          <td><h4>Cinza</h4></td>
          <td><h4>BR-32324</h4></td>
        </tr>
        <tr>
          <td><h4>Compass</h4></td>
          <td><h4>2023</h4></td>
          <td><h4>Cinza</h4></td>
          <td><h4>BR-32324</h4></td>
        </tr>
      </tbody>
      
    </table>
  </div>